CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS tenants (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), name TEXT NOT NULL, slug TEXT UNIQUE NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS users (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE, email TEXT NOT NULL, password_hash TEXT NOT NULL, role TEXT NOT NULL CHECK(role IN ('owner','admin','teacher','student')), status TEXT NOT NULL DEFAULT 'active', mfa_secret TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), UNIQUE(tenant_id,email));
CREATE TABLE IF NOT EXISTS curricula (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE, teacher_id UUID NOT NULL REFERENCES users(id), title TEXT NOT NULL, source_text TEXT NOT NULL, analysis JSONB, status TEXT NOT NULL DEFAULT 'draft', created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS lessons (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE, curriculum_id UUID NOT NULL REFERENCES curricula(id) ON DELETE CASCADE, teacher_id UUID NOT NULL REFERENCES users(id), title TEXT NOT NULL, content JSONB, status TEXT NOT NULL DEFAULT 'pending_review', reviewed_by UUID REFERENCES users(id), created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS assessments (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE, lesson_id UUID REFERENCES lessons(id) ON DELETE SET NULL, teacher_id UUID NOT NULL REFERENCES users(id), title TEXT NOT NULL, questions JSONB NOT NULL DEFAULT '[]', created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS assessment_attempts (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE, assessment_id UUID NOT NULL REFERENCES assessments(id) ON DELETE CASCADE, student_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE, answers JSONB NOT NULL DEFAULT '[]', score NUMERIC, submitted_at TIMESTAMPTZ);
CREATE TABLE IF NOT EXISTS usage_events (id BIGSERIAL PRIMARY KEY, tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE, user_id UUID REFERENCES users(id) ON DELETE SET NULL, kind TEXT NOT NULL, units NUMERIC NOT NULL DEFAULT 1, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS jobs (id BIGSERIAL PRIMARY KEY, tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE, type TEXT NOT NULL, payload JSONB NOT NULL, status TEXT NOT NULL DEFAULT 'queued', attempts INT NOT NULL DEFAULT 0, available_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS subscriptions (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE, stripe_customer_id TEXT, stripe_subscription_id TEXT UNIQUE, status TEXT NOT NULL, current_period_end TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE INDEX IF NOT EXISTS users_tenant_idx ON users(tenant_id); CREATE INDEX IF NOT EXISTS curricula_tenant_idx ON curricula(tenant_id); CREATE INDEX IF NOT EXISTS lessons_tenant_idx ON lessons(tenant_id); CREATE INDEX IF NOT EXISTS assessments_tenant_idx ON assessments(tenant_id); CREATE INDEX IF NOT EXISTS attempts_student_idx ON assessment_attempts(student_id); CREATE INDEX IF NOT EXISTS jobs_queue_idx ON jobs(status,available_at);
