-- EduAI V2-V4 expansion: adaptive learning, document RAG, billing, auditability and enterprise foundations.
ALTER TABLE users DROP CONSTRAINT IF EXISTS users_role_check;
ALTER TABLE users ADD CONSTRAINT users_role_check CHECK (role IN ('admin','teacher','student'));
CREATE TABLE IF NOT EXISTS topic_mastery (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE, student_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE, subject TEXT NOT NULL, topic TEXT NOT NULL, mastery NUMERIC(5,2) NOT NULL DEFAULT 0 CHECK (mastery BETWEEN 0 AND 100), evidence_count INTEGER NOT NULL DEFAULT 0 CHECK (evidence_count >= 0), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), UNIQUE(student_id,subject,topic));
CREATE INDEX IF NOT EXISTS topic_mastery_student_idx ON topic_mastery(tenant_id,student_id,mastery);
CREATE TABLE IF NOT EXISTS documents (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE, uploaded_by UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE, name TEXT NOT NULL CHECK (char_length(name) BETWEEN 1 AND 255), mime_type TEXT NOT NULL, size_bytes INTEGER NOT NULL CHECK (size_bytes > 0 AND size_bytes <= 20000000), created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS document_chunks (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), document_id UUID NOT NULL REFERENCES documents(id) ON DELETE CASCADE, tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE, chunk_index INTEGER NOT NULL CHECK (chunk_index >= 0), content TEXT NOT NULL CHECK (char_length(content) BETWEEN 1 AND 12000), created_at TIMESTAMPTZ NOT NULL DEFAULT now(), UNIQUE(document_id,chunk_index));
CREATE INDEX IF NOT EXISTS document_chunks_tenant_idx ON document_chunks(tenant_id,document_id);
CREATE TABLE IF NOT EXISTS subscription_plans (id TEXT PRIMARY KEY, name TEXT NOT NULL, stripe_price_id TEXT, monthly_ai_limit INTEGER NOT NULL CHECK (monthly_ai_limit >= 0), max_students INTEGER NOT NULL CHECK (max_students >= 0), max_teachers INTEGER NOT NULL CHECK (max_teachers >= 0), created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS subscriptions (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE, plan_id TEXT NOT NULL REFERENCES subscription_plans(id), stripe_customer_id TEXT, stripe_subscription_id TEXT UNIQUE, status TEXT NOT NULL CHECK (status IN ('trialing','active','past_due','canceled','incomplete','unpaid')), current_period_end TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE UNIQUE INDEX IF NOT EXISTS subscriptions_one_current_idx ON subscriptions(tenant_id) WHERE status IN ('trialing','active','past_due');
CREATE TABLE IF NOT EXISTS usage_counters (tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE, period_start DATE NOT NULL, ai_requests INTEGER NOT NULL DEFAULT 0 CHECK (ai_requests >= 0), PRIMARY KEY(tenant_id,period_start));
CREATE TABLE IF NOT EXISTS audit_logs (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE, actor_id UUID REFERENCES users(id) ON DELETE SET NULL, action TEXT NOT NULL CHECK (char_length(action) BETWEEN 1 AND 160), entity_type TEXT, entity_id UUID, metadata JSONB NOT NULL DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS audit_logs_tenant_idx ON audit_logs(tenant_id,created_at DESC);
INSERT INTO subscription_plans(id,name,monthly_ai_limit,max_students,max_teachers) VALUES ('free','Free',50,25,2),('teacher','Teacher',1000,200,10),('school','School',10000,5000,500),('enterprise','Enterprise',100000,100000,10000) ON CONFLICT(id) DO NOTHING;
DROP TRIGGER IF EXISTS subscriptions_updated_at ON subscriptions;
CREATE TRIGGER subscriptions_updated_at BEFORE UPDATE ON subscriptions FOR EACH ROW EXECUTE FUNCTION set_updated_at();
