const crypto = require('node:crypto');
const { query } = require('./db');
const SESSION_TTL_SECONDS = 60 * 60 * 24 * 7;
const secret = process.env.AUTH_SECRET;
function requireSecret() { if (!secret || secret.length < 32) throw new Error('AUTH_SECRET must be at least 32 characters.'); }
function hashPassword(password, salt = crypto.randomBytes(16).toString('hex')) { return `${salt}:${crypto.scryptSync(password, salt, 64).toString('hex')}`; }
function verifyPassword(password, stored) { const [salt, expected] = String(stored).split(':'); if (!salt || !expected) return false; const actual = crypto.scryptSync(password, salt, 64).toString('hex'); return actual.length === expected.length && crypto.timingSafeEqual(Buffer.from(actual), Buffer.from(expected)); }
function encodeToken(payload) { requireSecret(); const body = Buffer.from(JSON.stringify({ ...payload, exp: Math.floor(Date.now() / 1000) + SESSION_TTL_SECONDS })).toString('base64url'); const sig = crypto.createHmac('sha256', secret).update(body).digest('base64url'); return `${body}.${sig}`; }
function decodeToken(token) { requireSecret(); const [body, sig] = String(token || '').split('.'); if (!body || !sig) throw new Error('Invalid session'); const expected = crypto.createHmac('sha256', secret).update(body).digest('base64url'); if (sig.length !== expected.length || !crypto.timingSafeEqual(Buffer.from(sig), Buffer.from(expected))) throw new Error('Invalid session'); const payload = JSON.parse(Buffer.from(body, 'base64url').toString('utf8')); if (payload.exp < Math.floor(Date.now() / 1000)) throw new Error('Session expired'); return payload; }
function parseCookies(header = '') { const out = {}; for (const part of header.split(';')) { const i = part.indexOf('='); if (i > 0) out[part.slice(0, i).trim()] = decodeURIComponent(part.slice(i + 1)); } return out; }
function sessionCookie(token) { return `session=${encodeURIComponent(token)}; Path=/; Max-Age=${SESSION_TTL_SECONDS}; HttpOnly; SameSite=Lax${process.env.NODE_ENV === 'production' ? '; Secure' : ''}`; }
async function register({ email, password, role = 'student' }) { if (!/^\S+@\S+\.\S+$/.test(email)) throw new Error('Invalid email'); if (password.length < 10) throw new Error('Password must be at least 10 characters'); if (process.env.NODE_ENV === 'production' && role === 'teacher' && process.env.ALLOW_TEACHER_SIGNUP !== 'true') role = 'student'; if (!['student', 'teacher'].includes(role)) role = 'student'; const id = crypto.randomUUID(); const result = await query('INSERT INTO users (id,email,password_hash,role) VALUES ($1,$2,$3,$4) RETURNING id,email,role', [id, email.toLowerCase(), hashPassword(password), role]); return result.rows[0]; }
async function login({ email, password }) { const result = await query('SELECT id,email,password_hash,role FROM users WHERE email=$1', [email.toLowerCase()]); const user = result.rows[0]; if (!user || !verifyPassword(password, user.password_hash)) throw new Error('Invalid credentials'); const safeUser = { id: user.id, email: user.email, role: user.role }; return { user: safeUser, token: encodeToken({ sub: user.id, email: user.email, role: user.role }) }; }
function auth(required = true) { return (req, res, next) => { try { const header = req.get('authorization') || ''; const cookies = parseCookies(req.get('cookie') || ''); const token = header.startsWith('Bearer ') ? header.slice(7) : cookies.session; if (!token) { if (!required && process.env.NODE_ENV !== 'production') return next(); return res.status(401).json({ error: 'تسجيل الدخول مطلوب.' }); } req.user = decodeToken(token); next(); } catch { res.status(401).json({ error: 'جلسة الدخول غير صالحة.' }); } }; }
function requireRole(...roles) { return (req, res, next) => roles.includes(req.user?.role) ? next() : res.status(403).json({ error: 'ليس لديك صلاحية لهذا الإجراء.' }); }
module.exports = { register, login, auth, requireRole, sessionCookie };
